using ExcelHelper.NET.Core;
using ExcelHelper.NET.Extensions;
using ExcelHelper.NET.Models;
using NPOI.XSSF.UserModel;

namespace ExcelHelper.NET.Examples;

/// <summary>
/// Quick test để kiểm tra library hoạt động
/// </summary>
public static class QuickTest
{
    public static void RunTest()
    {
        // Test dữ liệu
        var data = new List<Person>
{
    new("Cassandra Fleming", 28, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Trevor Casey", 34, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Nicole Padilla", 30, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Turner", 32, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Miller", 34, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Matthew Martinez", 41, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Maria Morris", 30, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Carlos Zimmerman", 53, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Keith Lewis", 37, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Kimberly Wilson", 41, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("James Webb", 58, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Cunningham", 45, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mary Townsend", 44, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Julie Ellis", 44, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Jennifer Morris", 56, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Arthur Wilson", 22, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("John Davis", 44, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Gregory Morris", 58, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jenna Kerr", 47, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Jennifer Potts", 49, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Linda Li", 55, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Kristen Dunn", 43, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Karen Diaz", 23, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Erin Boyer", 35, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Smith", 52, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Dawn Chapman", 49, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("David Norris", 38, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Lamb", 35, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Kathleen Gamble", 59, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Diane Kennedy", 52, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Alexandra Torres", 40, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Nicole Smith", 41, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Mann", 40, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Ross Lin", 59, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Melanie Mills", 26, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Underwood", 34, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Katherine Montoya", 38, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Lee Conrad", 45, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Rachel Howard", 59, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Katherine Frazier", 27, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Jason Wilcox", 22, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Craig Baker", 41, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Banks", 47, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Wilson", 53, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Mary Washington", 36, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Julie Townsend", 40, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Cindy Johnston", 42, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Paul Williams", 42, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Laura Hodges", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Miguel Gray", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Lisa Curtis", 47, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Trevor Hansen", 44, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Joe Liu", 42, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Lindsay Simpson", 55, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("David Reynolds", 27, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Connie Key", 46, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Samuel Meadows", 26, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Brian Rojas", 49, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Knight", 52, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Adam Rodriguez", 32, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Shelby Williams", 29, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mariah Lamb", 21, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jose Wilson", 26, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Smith", 41, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Clinton Smith", 25, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Carl Olson DDS", 48, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("James Ferrell", 58, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Teresa Carroll", 50, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Melinda Poole", 46, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Zoe George", 34, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Rhonda Daugherty", 35, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Brett Mclaughlin", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Diane Edwards", 36, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Daniel White", 38, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Anne Lopez", 31, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Erica Smith", 48, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Hayes", 59, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Burke", 21, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Anthony Stokes", 60, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("William Williams", 60, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Danielle Yoder", 28, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Andre Roman", 53, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Maria Jones", 51, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Timothy Smith", 39, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Clark", 25, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Aaron Dickerson", 30, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Lisa Herring", 33, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Joseph Bass", 23, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("David Benitez", 24, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Catherine Fields", 36, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Kristen Williams", 32, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Nathan Good", 42, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Brittany Reed", 38, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Terry Hood", 51, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Angela Thomas", 51, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Ana Green", 45, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Eric Johnson", 44, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Michele Arnold", 40, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("James Archer", 29, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Wayne Cannon", 46, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Lori Sanders", 55, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Stephen Olson", 26, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Chris Santos", 24, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Gibson", 34, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Tracy Long", 25, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Mark Castro", 33, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Beth Lopez", 35, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Sharon Hall", 27, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mackenzie Wolfe", 26, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christina Terry", 60, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Gary Wilson", 59, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Gina Olson", 30, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Evelyn Johnson", 33, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Tiffany Cooper", 42, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("John Mejia", 48, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Patricia Henderson", 32, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Todd Ramos", 24, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Cassandra Fleming", 28, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Trevor Casey", 34, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Nicole Padilla", 30, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Turner", 32, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Miller", 34, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Matthew Martinez", 41, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Maria Morris", 30, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Carlos Zimmerman", 53, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Keith Lewis", 37, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Kimberly Wilson", 41, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("James Webb", 58, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Cunningham", 45, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mary Townsend", 44, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Julie Ellis", 44, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Jennifer Morris", 56, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Arthur Wilson", 22, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("John Davis", 44, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Gregory Morris", 58, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jenna Kerr", 47, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Jennifer Potts", 49, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Linda Li", 55, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Kristen Dunn", 43, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Karen Diaz", 23, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Erin Boyer", 35, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Smith", 52, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Dawn Chapman", 49, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("David Norris", 38, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Lamb", 35, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Kathleen Gamble", 59, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Diane Kennedy", 52, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Alexandra Torres", 40, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Nicole Smith", 41, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Mann", 40, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Ross Lin", 59, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Melanie Mills", 26, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Underwood", 34, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Katherine Montoya", 38, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Lee Conrad", 45, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Rachel Howard", 59, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Katherine Frazier", 27, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Jason Wilcox", 22, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Craig Baker", 41, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Banks", 47, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Wilson", 53, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Mary Washington", 36, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Julie Townsend", 40, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Cindy Johnston", 42, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Paul Williams", 42, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Laura Hodges", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Miguel Gray", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Lisa Curtis", 47, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Trevor Hansen", 44, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Joe Liu", 42, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Lindsay Simpson", 55, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("David Reynolds", 27, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Connie Key", 46, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Samuel Meadows", 26, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Brian Rojas", 49, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Knight", 52, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Adam Rodriguez", 32, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Shelby Williams", 29, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mariah Lamb", 21, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jose Wilson", 26, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Smith", 41, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Clinton Smith", 25, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Carl Olson DDS", 48, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("James Ferrell", 58, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Teresa Carroll", 50, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Melinda Poole", 46, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Zoe George", 34, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Rhonda Daugherty", 35, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Brett Mclaughlin", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Diane Edwards", 36, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Daniel White", 38, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Anne Lopez", 31, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Erica Smith", 48, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Hayes", 59, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Burke", 21, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Anthony Stokes", 60, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("William Williams", 60, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Danielle Yoder", 28, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Andre Roman", 53, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Maria Jones", 51, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Timothy Smith", 39, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Clark", 25, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Aaron Dickerson", 30, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Lisa Herring", 33, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Joseph Bass", 23, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("David Benitez", 24, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Catherine Fields", 36, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Kristen Williams", 32, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Nathan Good", 42, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Brittany Reed", 38, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Terry Hood", 51, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Angela Thomas", 51, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Ana Green", 45, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Eric Johnson", 44, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Michele Arnold", 40, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("James Archer", 29, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Wayne Cannon", 46, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Lori Sanders", 55, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Stephen Olson", 26, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Chris Santos", 24, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Gibson", 34, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Tracy Long", 25, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Mark Castro", 33, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Beth Lopez", 35, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Sharon Hall", 27, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mackenzie Wolfe", 26, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christina Terry", 60, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Gary Wilson", 59, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Gina Olson", 30, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Evelyn Johnson", 33, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Tiffany Cooper", 42, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("John Mejia", 48, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Patricia Henderson", 32, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Todd Ramos", 24, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Cassandra Fleming", 28, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Trevor Casey", 34, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Nicole Padilla", 30, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Turner", 32, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Miller", 34, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Matthew Martinez", 41, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Maria Morris", 30, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Carlos Zimmerman", 53, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Keith Lewis", 37, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Kimberly Wilson", 41, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("James Webb", 58, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Cunningham", 45, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mary Townsend", 44, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Julie Ellis", 44, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Jennifer Morris", 56, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Arthur Wilson", 22, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("John Davis", 44, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Gregory Morris", 58, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jenna Kerr", 47, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Jennifer Potts", 49, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Linda Li", 55, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Kristen Dunn", 43, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Karen Diaz", 23, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Erin Boyer", 35, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Smith", 52, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Dawn Chapman", 49, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("David Norris", 38, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Lamb", 35, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Kathleen Gamble", 59, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Diane Kennedy", 52, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Alexandra Torres", 40, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Nicole Smith", 41, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Mann", 40, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Ross Lin", 59, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Melanie Mills", 26, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Michael Underwood", 34, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Katherine Montoya", 38, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Lee Conrad", 45, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Rachel Howard", 59, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Katherine Frazier", 27, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Jason Wilcox", 22, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Craig Baker", 41, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Banks", 47, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Jessica Wilson", 53, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Mary Washington", 36, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Julie Townsend", 40, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Cindy Johnston", 42, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Paul Williams", 42, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Laura Hodges", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Miguel Gray", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Lisa Curtis", 47, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Trevor Hansen", 44, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Joe Liu", 42, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Lindsay Simpson", 55, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("David Reynolds", 27, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Connie Key", 46, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Samuel Meadows", 26, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Brian Rojas", 49, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Jesse Knight", 52, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Adam Rodriguez", 32, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Shelby Williams", 29, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mariah Lamb", 21, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Jose Wilson", 26, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Smith", 41, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Clinton Smith", 25, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Carl Olson DDS", 48, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("James Ferrell", 58, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Teresa Carroll", 50, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Melinda Poole", 46, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Zoe George", 34, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Rhonda Daugherty", 35, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Brett Mclaughlin", 40, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Diane Edwards", 36, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Daniel White", 38, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Anne Lopez", 31, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Erica Smith", 48, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Hayes", 59, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Robert Burke", 21, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Anthony Stokes", 60, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("William Williams", 60, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Danielle Yoder", 28, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Andre Roman", 53, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Maria Jones", 51, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Timothy Smith", 39, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Clark", 25, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Aaron Dickerson", 30, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Lisa Herring", 33, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Joseph Bass", 23, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("David Benitez", 24, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Catherine Fields", 36, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Kristen Williams", 32, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Nathan Good", 42, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Brittany Reed", 38, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Terry Hood", 51, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Angela Thomas", 51, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Ana Green", 45, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Eric Johnson", 44, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Michele Arnold", 40, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("James Archer", 29, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Wayne Cannon", 46, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Lori Sanders", 55, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Stephen Olson", 26, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Chris Santos", 24, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christopher Gibson", 34, "Coordinator", DateOnly.FromDateTime(DateTime.Now)),
    new("Tracy Long", 25, "Analyst", DateOnly.FromDateTime(DateTime.Now)),
    new("Mark Castro", 33, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Beth Lopez", 35, "Manager", DateOnly.FromDateTime(DateTime.Now)),
    new("Sharon Hall", 27, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Mackenzie Wolfe", 26, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("Christina Terry", 60, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Gary Wilson", 59, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Gina Olson", 30, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Evelyn Johnson", 33, "Administrator", DateOnly.FromDateTime(DateTime.Now)),
    new("Tiffany Cooper", 42, "Designer", DateOnly.FromDateTime(DateTime.Now)),
    new("John Mejia", 48, "Developer", DateOnly.FromDateTime(DateTime.Now)),
    new("Patricia Henderson", 32, "Consultant", DateOnly.FromDateTime(DateTime.Now)),
    new("Todd Ramos", 24, "Engineer", DateOnly.FromDateTime(DateTime.Now)),
    new("Danny Jones", 53, "Coordinator", DateOnly.FromDateTime(DateTime.Now))
};

        string templatePath = "D:\\test\\test.xlsx";
        string outputPath = "D:\\test\\test_output.xlsx";

        // Tạo ExcelDocument từ template
        var excelDoc = new ExcelDocument(templatePath, outputPath);
        // Thêm dữ liệu vào sheet đầu tiên
        var sheetManager = excelDoc.GetSheetManager("Sheet1");
        //sheetManager.Sheet.DeleteColumn(2);
        sheetManager.InsertDataToRange(data, "A1:G63");

        excelDoc.Save();

        Console.WriteLine("Dữ liệu đã được chèn vào file Excel thành công!");

    }
}

/// <summary>
/// Test model
/// </summary>
public record Person(string Name, int Age, string Job, DateOnly date);
